{
 "title": "Azure SQL Elastic Pool / Databases",
 "description": "Azure Monitor - SQL Elastic Pool and SQL Database metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscriptions",
    "query": {}
   },
   {
    "name": "ws",
    "label": "Workspaces",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Namespaces",
    "label": "Namespaces",
    "query": {}
   },
   {
    "name": "ResourceName",
    "label": "ResourceName",
    "query": {}
   },
   { "name": "Aggregation", "label": "Aggregation", "query": "Average,Maximum,Minimum" }
  ]
 },
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "cpu_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "DATA I/O %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "physical_data_read_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "LOG I/O %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "log_write_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "SPACE USED %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "storage_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "WORKERS %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "workers_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "SESSIONS %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "sessions_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU USED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "cpu_used",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU LIMIT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "cpu_limit",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "$Aggregation Compute Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "$Aggregation",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "cpu_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub",
     "subscriptions": [
      "3bc639b9-228f-40a6-b5d1-055cc84bb656"
     ]
    },
    {
     "azureMonitor": {
      "aggregation": "$Aggregation",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "physical_data_read_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "$Aggregation",
      "dimensionFilters": [],
      "metricDefinition": "$Namespaces",
      "metricName": "log_write_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Elastic Pool Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Aggregation CPU % by Database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "$Aggregation",
        "dimensionFilters": [
         { "dimension": "DatabaseResourceId", "filter": "", "operator": "eq" }
        ],
        "metricDefinition": "$Namespaces",
        "metricName": "cpu_percent",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub",
       "subscriptions": [
        "3bc639b9-228f-40a6-b5d1-055cc84bb656"
       ]
      }
     ]
    },
    {
     "title": "$Aggregation DATA IO % by Database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [
         { "dimension": "DatabaseResourceId", "filter": "", "operator": "eq" }
        ],
        "metricDefinition": "$Namespaces",
        "metricName": "physical_data_read_percent",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub",
       "subscriptions": [
        "3bc639b9-228f-40a6-b5d1-055cc84bb656"
       ]
      }
     ]
    },
    {
     "title": "$Aggregation LOG IO % by Database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [
         { "dimension": "DatabaseResourceId", "filter": "", "operator": "eq" }
        ],
        "metricDefinition": "$Namespaces",
        "metricName": "log_write_percent",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub",
       "subscriptions": [
        "3bc639b9-228f-40a6-b5d1-055cc84bb656"
       ]
      }
     ]
    },
    {
     "title": "DATA SPACE USED %",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "storage_percent",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "DATA USED",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "storage_used",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "ALLOCATED SPACE",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "allocated_data_storage",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "DATA MAX SIZE",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "storage_limit",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "connection_successful",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Failed Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "connection_failed",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Blocked By Firewall",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "blocked_by_firewall",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "deadlock",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "$Aggregation Workers %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "$Aggregation",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "workers_percent",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "$Aggregation Sessions %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "$Aggregation",
        "dimensionFilters": [],
        "metricDefinition": "$Namespaces",
        "metricName": "sessions_percent",
        "metricNamespace": "$Namespaces",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  }
 ]
}