{
 "title": "Pod Overview for AKS",
 "description": "Azure Monitor Container Insights - Pod and Container MetricsAzure Monitor for Containers sources collection of metrics as part of monitoring an AKS cluster. Out of the box, we can get dashboards for Node Level and Namespace level metrics in Grafana through App Insights and Log Analytics. This dashboard helps us to visualize pod level and container metric, and pod live logs.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "Workspace",
    "query": {}
   },
   {
    "name": "ResourceGroups",
    "query": {}
   },
   {
    "name": "AKS",
    "query": {}
   },
   {
    "name": "Namespace",
    "query": {}
   },
   {
    "name": "Pod",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Pod CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utlization - Current",
   "type": "table",
   "gridPos": { "h": 21, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where TimeGenerated > ago(2m)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where TimeGenerated > ago(2m)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'cpuLimitNanoCores'\n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | summarize arg_max(TimeGenerated, *) by ContainerName\n    | project ContainerName, CpuLimit=CounterValue\n    | join kind = inner (\n        Perf\n        | where TimeGenerated > ago(2m)\n        | where ObjectName == 'K8SContainer'\n        | where CounterName == 'cpuUsageNanoCores'\n        | where InstanceName contains '$AKS'\n        | extend ContainerNameParts = split(InstanceName, '/')\n        | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n        | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n        | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n        | summarize arg_max(TimeGenerated, *) by ContainerName\n        | project TimeGenerated, ContainerName, CpuUsage=CounterValue\n    ) on ContainerName\n) on ContainerName\n| order by Name asc\n| project Name, CpuLimit=(CpuLimit / 1000000), CpuUsage=(CpuUsage / 1000000)",
      "resultFormat": "table",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  {
   "title": "CPU Usage Per Pod ( in millicores )",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where $__timeFilter(TimeGenerated)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where $__timeFilter(TimeGenerated)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'cpuUsageNanoCores'\n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | project TimeGenerated, ContainerName, CounterValue\n) on ContainerName\n| order by TimeGenerated asc\n| project TimeGenerated, Name, CounterValue=(CounterValue / 1000000)",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  {
   "title": "Percentaqe Pod CPU Usage over Pod CPU Limit",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where $__timeFilter(TimeGenerated)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where $__timeFilter(TimeGenerated)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'cpuLimitNanoCores'\n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | summarize arg_max(TimeGenerated, *) by ContainerName\n    | project ContainerName, CpuLimit=CounterValue\n    | join kind = inner (\n        Perf\n        | where $__timeFilter(TimeGenerated)\n        | where ObjectName == 'K8SContainer'\n        | where CounterName == 'cpuUsageNanoCores'\n        | where InstanceName contains '$AKS'\n        | extend ContainerNameParts = split(InstanceName, '/')\n        | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n        | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n        | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n        | project TimeGenerated, ContainerName, CpuUsage=CounterValue\n    ) on ContainerName\n    | project TimeGenerated, ContainerName, CpuPercentage=(CpuUsage / CpuLimit) * 100\n) on ContainerName\n| order by TimeGenerated asc\n| project TimeGenerated, Name, CpuPercentage",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  { "title": "Pod Memory Usage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory Usage (Current)",
   "type": "table",
   "gridPos": { "h": 21, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where TimeGenerated > ago(2m)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where TimeGenerated > ago(2m)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'memoryLimitBytes'\n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | summarize arg_max(TimeGenerated, *) by ContainerName\n    | project ContainerName, MemLimit=CounterValue\n) on ContainerName\n| order by Name asc\n| project Name, MemLimit",
      "resultFormat": "table",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  {
   "title": "RSS Memory Usage Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where $__timeFilter(TimeGenerated)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where $__timeFilter(TimeGenerated)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'memoryRssBytes'    \n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | project TimeGenerated, ContainerName, CounterValue\n) on ContainerName\n| order by TimeGenerated asc\n| project TimeGenerated, Name, CounterValue=(CounterValue)",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  {
   "title": "Memory Working Set by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where $__timeFilter(TimeGenerated)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where $__timeFilter(TimeGenerated)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'memoryWorkingSetBytes'    \n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | project TimeGenerated, ContainerName, CounterValue\n) on ContainerName\n| order by TimeGenerated asc\n| project TimeGenerated, Name, CounterValue=(CounterValue)",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  {
   "title": "Percentage Memory(RSS) Usage against Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where $__timeFilter(TimeGenerated)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where $__timeFilter(TimeGenerated)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'memoryLimitBytes'\n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | summarize arg_max(TimeGenerated, *) by ContainerName\n    | project ContainerName, MemLimit=CounterValue\n    | join kind = inner (\n        Perf\n        | where $__timeFilter(TimeGenerated)\n        | where ObjectName == 'K8SContainer'\n        | where CounterName == 'memoryRssBytes'\n        | where InstanceName contains '$AKS'\n        | extend ContainerNameParts = split(InstanceName, '/')\n        | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n        | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n        | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n        | project TimeGenerated, ContainerName, MemUsage=CounterValue\n    ) on ContainerName\n    | project TimeGenerated, ContainerName, MemPercentage=(MemUsage / MemLimit) * 100\n) on ContainerName\n| order by TimeGenerated asc\n| project TimeGenerated, Name, MemPercentage",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  {
   "title": "Percentage Memory(Working Set) Usage against Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where $__timeFilter(TimeGenerated)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where $__timeFilter(TimeGenerated)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'memoryLimitBytes'\n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | summarize arg_max(TimeGenerated, *) by ContainerName\n    | project ContainerName, MemLimit=CounterValue\n    | join kind = inner (\n        Perf\n        | where $__timeFilter(TimeGenerated)\n        | where ObjectName == 'K8SContainer'\n        | where CounterName == 'memoryWorkingSetBytes'\n        | where InstanceName contains '$AKS'\n        | extend ContainerNameParts = split(InstanceName, '/')\n        | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n        | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n        | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n        | project TimeGenerated, ContainerName, MemUsage=CounterValue\n    ) on ContainerName\n    | project TimeGenerated, ContainerName, MemPercentage=(MemUsage / MemLimit) * 100\n) on ContainerName\n| order by TimeGenerated asc\n| project TimeGenerated, Name, MemPercentage",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  { "title": "Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where TimeGenerated > ago(30m)\n| where ClusterName == \"$AKS\"\n| where Namespace == \"$Namespace\"\n| summarize arg_max(TimeGenerated, *) by Name\n| project Pod=Name, Namespace, PodStatus, Node=Computer, PodRestartCount, ContainerRestartCount, PodStartTime, ControllerKind",
      "resultFormat": "table",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  {
   "title": "Pods per Namespaces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where TimeGenerated > ago(2m)\n| where ClusterName == \"$AKS\"\n| summarize arg_max(TimeGenerated, *) by Name\n| summarize qtd=count() by Namespace\n| project now(), Namespace, qtd",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  {
   "title": "Pod Count by Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "KubePodInventory\n| where $__timeFilter(TimeGenerated)\n| where ClusterName == \"$AKS\"\n| summarize count() by TimeGenerated, Namespace\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "7b0bcc15-eef6-4181-b9fe-23bc213ce163"
    }
   ]
  },
  { "title": "POD Live Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Live Logs",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let container_id = KubePodInventory | where Name == '$Pod' and ContainerID != '' | summarize count() by ContainerID | project ContainerID;\r\nContainerLog\r\n| where ContainerID in (container_id) and $__timeFilter(TimeGenerated)\r\n| order by TimeGenerated desc\r\n| project TimeGenerated, LogEntry",
      "resource": "/subscriptions/3bc639b9-228f-40a6-b5d1-055cc84bb656/resourceGroups/sc102"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "3bc639b9-228f-40a6-b5d1-055cc84bb656"
    }
   ]
  }
 ]
}